posts/urls.py
from django.urls import path,include

from . import views

app_name="posts"

urlpatterns = [
    path('', views.post_comment_create_list_view,name='all'),
    path("like-unlike/",views.like_unlike_post,name="like_unlike_post"),
    path("remove/<str:pk>/",views.remove,name="remove"),
    path("update/<str:pk>/",views.update,name="update"),
    path("search",views.search_method,name="search")
]

profiles/urls.py
from django.urls import path,include

from . import views
from .views import ProfileListView
app_name = "profiles"

urlpatterns = [
    path("myprofile/",views.my_profile,name="get_my_profile"),
    path("my-invites",views.invites_received_views,name="my_invites"),
    path("profile-list",ProfileListView.as_view(),name="profile_list"),
    path("invite-profile-list",views.invite_profile_list_views,name="invite_profile_list"),
    path("profile-details/<str:slug>/",views.get_profile_detail,name="get_profile_detail"),
    path("invitation",views.sent_invitation,name="sent_invitation"),
    path("remove_from_friends",views.remove_from_friend,name="remove_from_friend"),
    path("my-invites/reject/",views.reject_invitation,name="reject_invitation"),
    path("my-invites/accept/",views.accept_invitation,name="accept_invitation"),
    path("login",views.sign_in,name="login"),
    path("logout",views.sign_out,name="logout"),
    path("register",views.register,name="register")
]

socialmedia/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",home_view,name="home-view"),
    path("profiles/",include("profiles.urls")),
    path("posts/",include("posts.urls"),name="posts")
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from .utils import *
from django.template.defaultfilters import slugify
from django.db.models import Q
# Create your models here.

class ProfileManager(models.Manager):
    def get_all_profiles_to_invite(self,sender):
        profiles = Profile.objects.all().exclude(user=sender)    
        profile = Profile.objects.get(user=sender)
        qs = Relationship.objects.filter(Q(sender=profile) | Q(receiver=profile))
        accepted = set([])
        for rel in qs:
            if rel.status == "accepted":
                accepted.add(rel.receiver)
                accepted.add(rel.sender)
            
        available = [profile for profile in profiles if profile not in accepted]   
        return available
            
    def get_all_profiles(self,me):
        profiles = Profile.objects.all().exclude(user=me)
        return profiles



class Profile(models.Model):
    slug = models.SlugField(max_length=100, unique=True,blank=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100,blank=True)
    bio = models.TextField(default="no bio...")
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    country = models.CharField(max_length=50)
    avatar = models.ImageField(upload_to="profile_images",default="avatar.jpg")
    friends = models.ManyToManyField(User,blank=True,related_name='friends')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    objects = ProfileManager()
    
    def get_friends(self):
        return self.friends.all()
    
    def get_friends_no(self):
        return self.friends.all().count()
    
    def get_posts_no(self):
        return self.posts.all().count() 
    
    def get_likes_given_no(self):
        likes = self.like_set.all()
        total_likes = 0
        for like in likes:
            if like == "Like":
                total_likes += 1
        return total_likes
    
    def get_likes_received_no(self):
        posts = self.posts.all()
        total_likes = 0
        for post in posts:
            total_likes += post.liked.all().count()
        return total_likes
    
    def __str__(self):
        return f"{self.user.username}-{self.created.strftime('%d-%m-%Y')}"
    
    def save(self,*args,**kwargs):
        ex = False
        if self.first_name and self.last_name:
            to_slug = slugify(str(self.first_name) +' '+ str(self.last_name))
            ex = Profile.objects.filter(slug=to_slug).exists()
            while ex:
                to_slug = slugify(to_slug +' '+ str(get_unique_id()))
                ex = Profile.objects.filter(slug=to_slug).exists()
            self.slug = to_slug
        else:
            to_slug = slugify(self.user)
        self.slug = to_slug
        super().save(*args,**kwargs)
        
class RelationshipManger(models.Manager):
    def invatations_received(self,receiver):
        qs = Relationship.objects.filter(receiver=receiver,status="send")
        return qs    

class Relationship(models.Model):
    STATUS_CHOICES = (
    ('send', 'send'),
    ('accepted', 'accepted')
)
    sender = models.ForeignKey(Profile,on_delete=models.CASCADE,related_name='sender')
    receiver = models.ForeignKey(Profile,on_delete=models.CASCADE,related_name='receiver')
    status = models.CharField(max_length=10,choices=STATUS_CHOICES)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    objects = RelationshipManger()
    
    def __str__(self):
        return f"{self.sender}-{self.receiver}-{self.status}"
    

profiles/forms.py
from .models import *
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class ProfileModelForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'bio', 'avatar')
        
class Register(UserCreationForm):
    class Meta:
        model = User
        fields = ("username","email","password1","password2")

profiles/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import *
from .forms import *
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from posts.models import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout

# Create your views here.
@login_required(login_url="profiles:login")
def my_profile(request):
    profile = Profile.objects.get(user=request.user)
    form = ProfileModelForm(instance=profile)
    confirm = False
    if request.method == "POST":
        form = ProfileModelForm(request.POST or None,request.FILES or None,instance=profile)
        if form.is_valid():
            form.save()
            confirm = True
    context = {'profile': profile,"form":form,"confirm":confirm}
    return render(request, 'profiles/myprofile.html', context)

@login_required(login_url="profiles:login")
def invites_received_views(request):
    profile = Profile.objects.get(user=request.user)
    qs = Relationship.objects.invatations_received(profile)
    context = {'qs': qs}
    return render(request, 'profiles/invites_received.html', context)

@login_required(login_url="profiles:login")
def accept_invitation(request):
    if request.method=="POST":
        pk = request.POST.get('profile_pk')
        sender = Profile.objects.filter(pk=pk).first()
        receiver = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        if rel.status == 'send':
            rel.status = 'accepted'
            rel.save()
    return redirect("profiles:my_invites")

@login_required(login_url="profiles:login")
def reject_invitation(request):
    if request.method=="POST":
        pk = request.POST.get("profile_pk")
        receiver = Profile.objects.get(user=request.user)
        sender = Profile.objects.filter(pk=pk).first()
        rel = Relationship.objects.filter(sender=sender, receiver=receiver).first()
        rel.delete()
    return redirect("profiles:my_invites")
        
@login_required(login_url="profiles:login")
def invite_profile_list_views(request):
    user = request.user
    qs = Profile.objects.get_all_profiles_to_invite(user)
    context = {'qs': qs}
    return render(request, 'profiles/invite_profile_list.html', context)

class ProfileListView(LoginRequiredMixin, ListView):
    model = Profile
    template_name = 'profiles/profile_list.html'
    # context_object_name = 'qs'

    def get_queryset(self):
        qs = Profile.objects.get_all_profiles(self.request.user)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=self.request.user)
        profile = Profile.objects.get(user=user)
        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(receiver=profile)
        rel_receiver = []
        rel_sender = []
        for item in rel_r:
            rel_receiver.append(item.receiver.user)
        for item in rel_s:
            rel_sender.append(item.sender.user)
        context["rel_receiver"] = rel_receiver
        context["rel_sender"] = rel_sender
        context['is_empty'] = False
        if len(self.get_queryset()) == 0:
            context['is_empty'] = True

        return context

@login_required(login_url="profiles:login")
def get_profile_detail(request,slug):
    profile = Profile.objects.get(slug=slug)
    posts = Post.objects.filter(author=profile)
    context = {"profile":profile,"posts":posts}
    return render(request, 'profiles/profile_detail.html', context)


@login_required(login_url="profiles:login")
def sent_invitation(request):
    if request.method == "POST":
        pk = request.POST.get("profile_pk")
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)
        
        rel = Relationship.objects.create(sender=sender,receiver=receiver,status="send")
        
        return redirect('profiles:profile_list')
    
@login_required(login_url="profiles:login")
def remove_from_friend(request):
    if request.method == "POST":
        pk = request.POST.get("profile_pk")
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)
        
        rel = Relationship.objects.filter((Q(sender=sender) & Q(receiver=receiver) | Q(sender=receiver) & Q(receiver=sender)))
        
        rel.delete()
        
        return redirect('profiles:profile_list')    
    
def sign_in(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('posts:all')
        return render(request,'profiles/sign_in.html')
    return render(request,'profiles/sign_in.html')

@login_required(login_url="profiles:login")
def sign_out(request):
    logout(request)
    return redirect('profiles:login')

def register(request):
    form = Register()
    if request.method == "POST":
        form = Register(request.POST)
        if form.is_valid():
            form.save()
            return redirect('profiles:login')
    context = {"form":form}
    return render(request,'profiles/register.html',context)

profiles/templates/profiles/get_my_profile.html
{% extends 'base.html' %}

{% block title %}
profile detail
{% endblock title %}

{% block content %}
<div class="ui grid">
    <br>
    <div class="row">
        <div class="four wide column">
            <img class="ui medium rounded image" src={{profile.avatar.url}}>
            <h1>{{profile.user}}</h1>
            <div class="ui vertical fluid menu">
                <div class="item">
                    Posts
                    <div class="ui label">{{ profile.get_posts_no }}</div>
                </div>
                <div class="item">
                    Likes given
                    <div class="ui label">{{ profile.get_likes_given_no }}</div>
                </div>
                <div class="item">
                    Likes received
                    <div class="ui label">{{ profile.get_likes_received_no }}</div>
                </div>
                <div class="item">
                    Friends
                    <div class="ui label">{{ profile.get_friends_no }}</div>
                </div>
            </div>

            {% if object.user not in rel_receiver and object.user not in rel_sender %}
                <form action="{% url 'profiles:send-invite' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="profile_pk" value={{object.pk}}>
                    <button type="submit" class="ui positive basic button mb-5 w-big"><i class="plus square icon"></i>Add to friends</button>
                </form>
            {% endif %}

            {% if object.user in rel_receiver and request.user not in object.friends.all %}
                <button class="ui disabled button mb-5 w-big"><i class="user icon"></i>Waiting for approval</button>
            {% endif %}

        </div>
        <div class="twelve wide column">
            {% if  posts %}
                {% for post in posts %}
                    <div class="segment ui fluid">
                        {{post.content}}
                    </div>
                {% endfor %}
            {% else %}
                    This user has no posts.
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

profiles/templates/profiles/invite_profile_list.html
{% extends 'base.html' %}

{% block title %}
invite friends
{% endblock title %}

{% block content %}
    <ul>
        {% for item in qs %}
            <li>{{item}}</li>
        {% endfor %}
    </ul>
{% endblock content %}

profiles/templates/profiles/invites_received.html
{% extends 'base.html' %}

{% block title %}
my invites
{% endblock title %}

{% block content %}
{% if qs %}
    {% for obj in qs %}
        <div class="ui segment">
            <div class="ui grid">
                <div class="row">
                    <div class="three wide column">
                        <img class="ui small circular image" src={{obj.sender.avatar.url}}>
                    </div>
                    <div class="thirteen wide column">
                        <h3>{{obj.sender.user}}</h3>
                        <p>{{obj.sender.bio}}</h3>
                        <br>
                        <a href="{% url 'profiles:get_profile_detail' obj.sender.slug %}">
                            <button class="ui primary button w-big mb-5">See profile</button>
                        </a>
                        <form action="{% url 'profiles:accept_invitation' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value="{{obj.sender.pk}}">
                            <button type="submit" class="ui positive basic button w-big mb-5">
                                <i class="check icon"></i>
                                Accept invite
                            </button>
                        </form>
                         <form action="{% url 'profiles:reject_invitation' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{obj.sender.pk}}>
                            <button type="submit" class="ui negative basic button w-big mb-5">
                                <i class="close icon"></i>
                                Reject invite
                            </button>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    {% endfor %}
{% else %}
<h1>There is no request</h1>
{% endif %}
{% endblock content %}

profiles/templates/profiles/myprofile.html
{% extends 'base.html' %}

{% block title %}
my profile
{% endblock title %}

{% block content %}

<!-- MODAL -->
<div class="ui modal mymodal">
  <i class="close icon"></i>
  <div class="header">
    Update your Profile
  </div>
  <div class="image content">
    <div class="ui medium image">
      <img src="{{profile.avatar.url}}">
    </div>
    <div class="description">
      <div class="ui header">Provide some additional/newest info about you </div>
     <form action="" method="POST" class="ui form" enctype='multipart/form-data'>
        {% csrf_token %}
        {{form.as_p}}
    </div>
  </div>
  <div class="actions">
    <button type='submit' class="ui positive right labeled icon button">
      Update
      <i class="checkmark icon"></i>
    </button>
    </form>
  </div>
</div>



<div class="ui segment">
    {% if confirm %}
        <div class="ui green message">Your profile has been updated</div>
    {% endif %}
    <h3>my profile: {{request.user}}</h3>
    <div class="ui grid">
        <div class='row'>
            <div class='six wide column'>
                <img class="ui medium rounded image" src={{profile.avatar.url}}>
                <div class="row mt-5">
                    <button class='ui secondary button' id='modal-btn'>Update your profile</button>
                </div>
            </div>
            <div class="ten wide column">
                <table class="ui table">
                    <tbody>
                        <tr>
                            <td>username</td>
                            <td>{{profile.user}}</td>
                        </tr>
                        <tr>
                            <td>first name</td>
                            <td>{{profile.first_name}}</td>
                        </tr>
                        <tr>
                            <td>last name</td>
                            <td>{{profile.last_name}}</td>
                        </tr>
                        <tr>
                            <td>bio</td>
                            <td>{{profile.bio}}</td>
                        </tr>
                        <tr>
                            <td>number of friends</td>
                            <td>{{profile.get_friends_no}}</td>
                        </tr>
                        <tr>
                            <td>Friends</td>
                            <td>
                                {% for profile in profile.get_friends %}
                                <li>{{ profile }}</li>
                                {% endfor %}
                            </td>
                        </tr>
                        <tr>
                            <td>number of posts</td>
                            <td>{{profile.get_posts_no}}</td>
                        </tr>
                        <tr>
                            <td>number of likes given</td>
                            <td>{{profile.get_likes_given_no}}</td>
                        </tr>
                        <tr>
                            <td>number of likes received</td>
                            <td>{{profile.get_likes_received_no}}</td>
                        </tr>

                        
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

profiles/templates/profiles/profile_detail.html
{% extends 'base.html' %}

{% block title %}
profile detail
{% endblock title %}

{% block content %}
<div class="ui grid">
    <br>
    <div class="row">
        <div class="four wide column">
            <img class="ui medium rounded image" src={{profile.avatar.url}}>
            <h1>{{profile.user}}</h1>
            <div class="ui vertical fluid menu">
                <div class="item">
                    Posts
                    <div class="ui label">{{ profile.get_posts_no }}</div>
                </div>
                <div class="item">
                    Likes given
                    <div class="ui label">{{ profile.get_likes_given_no }}</div>
                </div>
                <div class="item">
                    Likes received
                    <div class="ui label">{{ profile.get_likes_received_no }}</div>
                </div>
                <div class="item">
                    Friends
                    <div class="ui label">{{ profile.get_friends_no }}</div>
                </div>
            </div>

            {% if object.user not in rel_receiver and object.user not in rel_sender %}
                <form action="{% url 'profiles:send-invite' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="profile_pk" value={{object.pk}}>
                    <button type="submit" class="ui positive basic button mb-5 w-big"><i class="plus square icon"></i>Add to friends</button>
                </form>
            {% endif %}

            {% if object.user in rel_receiver and request.user not in object.friends.all %}
                <button class="ui disabled button mb-5 w-big"><i class="user icon"></i>Waiting for approval</button>
            {% endif %}

        </div>
        <div class="twelve wide column">
            {% if  posts %}
                {% for post in posts %}
                    <div class="segment ui fluid">
                        {{post.content}}
                    </div>
                {% endfor %}
            {% else %}
                    This user has no posts.
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

profiles/templates/profiles/profile_list.html
{% extends 'base.html' %}

{% block title %}
all profiles
{% endblock title %}

{% block content %}

    {% if is_empty %}
        <h1>No profiles to interact with</h1>
    {% endif %}

    {% for obj in object_list %}
        <div class="ui segment">
            <div class="ui grid">
                <div class="row">
                    <div class="three wide column">
                        <img class="ui small circular image" src={{obj.avatar.url}}>
                    </div>
                    <div class="thirteen wide column">
                        <h3>{{obj.user}}</h3>
                        <p>{{obj.bio}}</p>
                        <a href="{% url 'profiles:get_profile_detail' obj.slug %}"><button class="ui primary button mb-5 w-big">See profile</button></a>
                        <br>
                        {% if obj.user not in rel_receiver and obj.user not in rel_sender %}
                        <form action="{% url 'profiles:sent_invitation' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{obj.pk}}>
                            <button type="submit" class="ui positive basic button mb-5 w-big"><i class="plus square icon"></i>Add to friends</button>
                        </form>
                        {% endif %}

                        {% if obj.user in rel_receiver and request.user not in obj.friends.all %}
                            <button class="ui disabled button mb-5 w-big"><i class="user icon"></i>Waiting for approval</button>
                        {% endif %}

                        {% if request.user in obj.friends.all %}
                        <form action="{% url 'profiles:remove_from_friend' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{obj.pk}}>
                            <button type="submit" class="ui negative basic button mb-5 w-big"><i class="minus square icon"></i>Remove from friends</button>
                        </form>
                        {% endif %}

                    </div>

                </div>
            </div>
        </div>
    {% endfor %}
{% endblock content %}

profiles/templates/profiles/register.html
{% extends "base.html" %}
{% block title %}Register{% endblock title %}
{% block content %}
<section class="vh-100" style="background-color: #eee;">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-12 col-xl-11">
          <div class="card text-black" style="border-radius: 25px;">
            <div class="card-body p-md-5">
              <div class="row justify-content-center">
                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
  
                  <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign up</p>
  
                  <form action="" method="POST" class="mx-1 mx-md-4">
                        {% csrf_token %}
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <input type="text" name="username" class="form-control" />
                        <label class="form-label" for="form3Example1c">Your Name</label>
                      </div>
                    </div>
  
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <input type="email" name="email" class="form-control" />
                        <label class="form-label" for="form3Example3c">Your Email</label>
                      </div>
                    </div>
  
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <input type="password"  name="password1" class="form-control" />
                        <label class="form-label" for="form3Example4c">Password</label>
                      </div>
                    </div>
  
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <input type="password" name="password2" class="form-control" />
                        <label class="form-label" for="form3Example4cd">Repeat your password</label>
                      </div>
                    </div>

                    <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                      <button type="submit" class="btn btn-primary btn-lg">Register</button>
                    </div>
  
                  </form>
  
                </div>
                <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
  
                  <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                    class="img-fluid" alt="Sample image">
  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

profiles/templates/profiles/sign_in.html
{% extends 'base.html' %}
{% block title%}login{% endblock %}
{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    <!-- Email input -->
    <div class="form-outline mb-4">
      <input type="text" name="username" class="form-control" />
      <label class="form-label" >Username</label>
    </div>
  
    <!-- Password input -->
    <div class="form-outline mb-4">
      <input type="password" name="password" class="form-control" />
      <label class="form-label">Password</label>
    </div>
  
  
    <!-- Submit button -->
    <button type="submit" class="btn btn-primary btn-block mb-4">Sign in</button>
</form>
  
    <!-- Register buttons -->
    <div class="text-center">
      <p>Not a member? <a href="{% url 'profiles:register' %}">Register</a></p>
      <p>or sign up with:</p>
      <button type="button" class="btn btn-link btn-floating mx-1">
        <i class="fab fa-facebook-f"></i>
      </button>
  
      <button type="button" class="btn btn-link btn-floating mx-1">
        <i class="fab fa-google"></i>
      </button>
  
      <button type="button" class="btn btn-link btn-floating mx-1">
        <i class="fab fa-twitter"></i>
      </button>
  
      <button type="button" class="btn btn-link btn-floating mx-1">
        <i class="fab fa-github"></i>
      </button>
    </div>
{% endblock %}