posts/urls.py
from django.urls import path,include

from . import views

app_name="posts"

urlpatterns = [
    path('', views.post_comment_create_list_view,name='all'),
    path("like-unlike/",views.like_unlike_post,name="like_unlike_post"),
    path("remove/<str:pk>/",views.remove,name="remove"),
    path("update/<str:pk>/",views.update,name="update"),
    path("search",views.search_method,name="search")
]

profiles/urls.py
from django.urls import path,include

from . import views
from .views import ProfileListView
app_name = "profiles"

urlpatterns = [
    path("myprofile/",views.my_profile,name="get_my_profile"),
    path("my-invites",views.invites_received_views,name="my_invites"),
    path("profile-list",ProfileListView.as_view(),name="profile_list"),
    path("invite-profile-list",views.invite_profile_list_views,name="invite_profile_list"),
    path("profile-details/<str:slug>/",views.get_profile_detail,name="get_profile_detail"),
    path("invitation",views.sent_invitation,name="sent_invitation"),
    path("remove_from_friends",views.remove_from_friend,name="remove_from_friend"),
    path("my-invites/reject/",views.reject_invitation,name="reject_invitation"),
    path("my-invites/accept/",views.accept_invitation,name="accept_invitation"),
    path("login",views.sign_in,name="login"),
    path("logout",views.sign_out,name="logout"),
    path("register",views.register,name="register")
]

socialmedia/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",home_view,name="home-view"),
    path("profiles/",include("profiles.urls")),
    path("posts/",include("posts.urls"),name="posts")
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/main/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}

{% block content %}
<h3>Hello</h3>
{{user}}
{% endblock content %}

{% block scripts %}
<script>
$(document).ready(function(){
    console.log('working')
})
</script>
{% endblock  %}

templates/main/navbar.html
<div class="ui inverted menu">
    <div class="ui container">
      <a href="" class="item">
          <h3>bffbook</h3>
      </a>
      {% if request.user.is_authenticated %}
      <a href="/" class="item">
          Home
      </a>
      <a href="{% url 'posts:all' %}" class="item">
        Posts
    </a>
    {% endif %}
  
      <div class="right menu">
          {% if request.user.is_authenticated %}
          <div class="item">
              <div class="ui floating dropdown icon button teal"> Friends
                  <i class="dropdown icon"></i>
                  <div class="menu">
                      <a href="{% url 'profiles:profile_list' %}" class="item">
                          All Profiles
                      </a>
                      <a href="{% url 'profiles:invite_profile_list' %}" class="item">
                          Send Invites
                      </a>
                      <a href="{% url 'profiles:my_invites' %}" class="item">
                          Received Invites
                          <strong>{{invitations}}</strong>
                      </a>
                  </div>
               </div>
          </div>
               <div class="item">
                <form action="{% url 'posts:search' %}" method="POST">
                    {% csrf_token %}
                  <div class="ui action left icon input">
                  <input class="prompt" type="text" name='search' placeholder="name of a friend...">
                  <i class="search icon"></i>
                  <button type='submit' class="ui button">Search</button>
                  </div>
              </form>
              </div>
              <a href="{% url 'profiles:get_my_profile' %}" class="item">
                    <img src={{ profile_pic.url }} class="ui avatar image">&nbsp;
                   {{ request.user }}
              </a>
              
              <a href="{% url 'profiles:logout' %}" class="ui item">
                  Logout
              </a>
          {% else %}
          <a href="{% url 'profiles:login' %}" class="ui item">
                  Login
              </a>
          {% endif %}
      </div>
    </div>
  </div>