posts/urls.py
from django.urls import path,include

from . import views

app_name="posts"

urlpatterns = [
    path('', views.post_comment_create_list_view,name='all'),
    path("like-unlike/",views.like_unlike_post,name="like_unlike_post"),
    path("remove/<str:pk>/",views.remove,name="remove"),
    path("update/<str:pk>/",views.update,name="update"),
    path("search",views.search_method,name="search")
]

profiles/urls.py
from django.urls import path,include

from . import views
from .views import ProfileListView
app_name = "profiles"

urlpatterns = [
    path("myprofile/",views.my_profile,name="get_my_profile"),
    path("my-invites",views.invites_received_views,name="my_invites"),
    path("profile-list",ProfileListView.as_view(),name="profile_list"),
    path("invite-profile-list",views.invite_profile_list_views,name="invite_profile_list"),
    path("profile-details/<str:slug>/",views.get_profile_detail,name="get_profile_detail"),
    path("invitation",views.sent_invitation,name="sent_invitation"),
    path("remove_from_friends",views.remove_from_friend,name="remove_from_friend"),
    path("my-invites/reject/",views.reject_invitation,name="reject_invitation"),
    path("my-invites/accept/",views.accept_invitation,name="accept_invitation"),
    path("login",views.sign_in,name="login"),
    path("logout",views.sign_out,name="logout"),
    path("register",views.register,name="register")
]

socialmedia/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",home_view,name="home-view"),
    path("profiles/",include("profiles.urls")),
    path("posts/",include("posts.urls"),name="posts")
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models

from profiles.models import Profile
# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(Profile,on_delete=models.CASCADE,related_name="posts")
    content = models.TextField()
    image = models.ImageField(upload_to="posts",blank=True)
    liked = models.ManyToManyField(Profile,blank=True, related_name='likes')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return str(self.content[:20])
    
    def num_likes(self):
        return self.liked.all().count()
    
    def num_comments(self):
        return self.comment_set.all().count()    
    
    def get_all_authors_posts(self):
        return self.comment_set.all()

    
    class Meta:
        ordering =("-created",)
        
class Comment(models.Model):
    author = models.ForeignKey(Profile,on_delete=models.CASCADE)
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    body = models.TextField(max_length=100)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return str(self.pk)

LIKE_CHOICES =(
    ('Like','Like'),('Unlike','Unlike')
)
class Like(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    user = models.ForeignKey(Profile,on_delete=models.CASCADE)
    value = models.CharField(max_length=8,choices=LIKE_CHOICES)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.user}-{self.post}-{self.value}"

posts/forms.py
from .models import *

from django import forms

class PostModelForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={'rows':2}))
    class Meta:
        model = Post
        fields = ("content","image")
        
class CommentModelForm(forms.ModelForm):
    body = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder': 'Add a comment...'}))
    class Meta:
        model = Comment
        fields = ("body",)

posts/views.py
from django.shortcuts import render,redirect
from .models import *
from .forms import *
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.db.models import Q
# Create your views here.


@login_required(login_url="profiles:login")
def post_comment_create_list_view(request):
    qs = Post.objects.all()
    profile = Profile.objects.get(user=request.user)
    
    p_form = PostModelForm()
    c_form = CommentModelForm()
    post_added = False
    
    profile = Profile.objects.get(user=request.user)
    
    if "submit_p_form" in request.POST:
        p_form = PostModelForm(request.POST, request.FILES)
        if p_form.is_valid():
            obj = p_form.save(commit=False)
            obj.author = profile
            obj.save()
            p_form = PostModelForm()
            post_added = True
    
    if request.method == "POST":
        c_form = CommentModelForm(request.POST)
        if c_form.is_valid():
            obj = c_form.save(commit=False)
            obj.author = profile
            obj.post = Post.objects.get(id=request.POST.get("post_id"))
            obj.save()
            c_form = CommentModelForm()

    
    context = {
        'qs': qs,
        "profile":profile,
        "p_form":p_form,
        "c_form":c_form,
        "post_added":post_added,
    }
    return render(request, 'posts/main.html', context)
    
@login_required(login_url="profiles:login")
def like_unlike_post(request):
    user = request.user
    if request.method == "POST":
        post_id = request.POST.get("post_id")
        post_model = Post.objects.get(id=post_id)
        profile = Profile.objects.get(user=user)
        if profile in post_model.liked.all():
            post_model.liked.remove(profile)
        else:
            post_model.liked.add(profile)

        like,created = Like.objects.get_or_create(user=profile,post_id=post_id)
    
        if not created:
            if like.value == "Like":
                like.value = "Unlike"
            else:
                like.value ="Like"
                
        else:
            like.value = "Like"
            
            post_model.save()
            like.save()
            
        
        return redirect("posts:all")
        
@login_required(login_url="profiles:login")
def remove(request,pk):
    post = Post.objects.get(id=pk)
    if request.user == post.author.user:
        if request.method == "POST":
            post.delete()
            return redirect("posts:all")
    return render(request, 'posts/remove.html')

@login_required(login_url="profiles:login")
def update(request,pk):
    post = Post.objects.get(id=pk)
    form = PostModelForm(instance=post)
    if request.user == post.author.user:
        if request.method == "POST":
            form = PostModelForm(request.POST, request.FILES, instance=post)
            if form.is_valid():
                form.save()
                return redirect("posts:all")
    else:
        return redirect("posts:all")
    
    context = {"form":form}
    return render(request, 'posts/update.html', context)

@login_required(login_url="profiles:login")
def search_method(request):
    if request.method == "POST":
        search = request.POST.get("search")
        profiles = Profile.objects.filter(Q(user__username__icontains=search)).exclude(user=request.user)
        
    context = {"profiles":profiles}
    return render(request, 'posts/search.html', context)

posts/templates/posts/main.html
{% extends 'base.html' %}
{% load static %}
{% block title %}main page{% endblock title %}

{% block content %}
<div class="ui grid">
    <div class="eleven wide column">
        {% for obj in qs %}

        <div class="ui fluid card">
            <div class="content">
                <div class="right floated meta">
                    <div class="ui grid">
                        <div class="row">
                            {% if request.user == obj.author.user  %}
                                <a href="{% url 'posts:update' obj.pk %}"><button class="ui button bwhite-lg ">Update</button></a>
                                <a href="{% url 'posts:remove' obj.pk %}"><button class="ui button bwhite-lg ">Delete</button></a>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <img class="ui avatar image" src={{obj.author.avatar.url}}>
               {{ obj.author.user }}- {{ obj.created|timesince}} ago
            </div>
            <div class="ui fluid image">
                {% if obj.image %}
                    <img src={{obj.image.url}}>
                {% endif %}
            </div>
            <div class="content">
                <p> {{ obj.content }} </p>
                <div class="right floated">
                    <form action="{% url 'posts:like_unlike_post' %}" method="POST" class='like-form' id='{{obj.id}}'>
                        {% csrf_token %}
                        <input type="hidden" name="post_id" value={{obj.id}}>
                        
                            <button type="submit" class="ui button like-btn{{obj.id}}">
                                {% if profile not in obj.liked.all %}
                                    Like
                                {% else %}
                                    Unlike
                                {% endif %}
                            </button>
                            <div class="ui grid">
                                <div class="column">
                                    <div class="like-count{{obj.id}}"> {{obj.num_likes}} </div>
                                </div>
                                <div class="column">
                                    likes
                                </div>
                            </div>
                    </form>
                </div>
                <i class="comment icon"></i>
                <span> {{ obj.num_comments }} comments</span>
            </div>
            <div class="extra content">
                <div class="mb-5">
                  
                </div>
                <button class="cmt_btn ui button mb-5">show / hide comments</button>
                <div class="comment-box">
                {% if obj.comment_set.all %}
                    {% for c in obj.comment_set.all %}
                    
                        <div class="ui segment mb-5">
                            <img class="ui avatar image" src={{c.author.avatar.url}}>
                            <span>{{ c.user }}</span>
                            <div class='mt-5'>{{ c.body }}</div>
                        </div>
                    
                    {% endfor %}
                {% endif %}
                </div>
  
                <form action="" method="POST"class='ui fluid form'>
                    {% csrf_token %}
                    <input type="hidden" name="post_id" value={{obj.id}}>
                    {{ c_form }}
                    <button type="submit" name="submit_c_form" class="ui primary button mt-5 w-full">Send</button>
                </form>
            </div>
        </div>


        {% endfor %}
    </div>
    <div class="five wide column">
        <div class="ui segment">
            {% if post_added %}
                <div class="ui green message">Post added</div>
            {% endif %}
            <form action="" method="POST" class='ui form' enctype="multipart/form-data">
                {% csrf_token %}
                {{p_form}}
                <button type='submit' name="submit_p_form" class="ui positive button w-full mt-5">Post</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}
{% block scripts %} 
    <script>
        $( document ).ready(function() {
            let display = false
            $(".cmt_btn").click(function () {
                if (display===false) {
                    $(this).next(".comment-box").show("slow");
                    display=true
                } else {
                    $(this).next(".comment-box").hide("slow");
                    display=false
                }  
            });

            $('.like-form').submit(function(e){
                e.preventDefault()
                
                const post_id = $(this).attr('id')
                
                const likeText = $(`.like-btn${post_id}`).text()
                const trim = $.trim(likeText)

                const url = $(this).attr('action')
                
                let res;
                const likes = $(`.like-count${post_id}`).text()
                const trimCount = parseInt(likes)
                
                $.ajax({
                    type: 'POST',
                    url: url,
                    data: {
                        'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
                        'post_id':post_id,
                    },
                    success: function(response) {
                        if(trim === 'Unlike') {
                            $(`.like-btn${post_id}`).text('Like')
                            res = trimCount - 1
                        } else {
                            $(`.like-btn${post_id}`).text('Unlike')
                            res = trimCount + 1
                        }

                        $(`.like-count${post_id}`).text(res)
                    },
                    error: function(response) {
                        console.log('error', response)
                    }
                })

            })
        });
    </script>
{% endblock scripts %}

posts/templates/posts/remove.html
{% extends 'base.html' %}
{% block title %}
Delete post
{% endblock %}
{% block content %}
<div class="ui segment">
    <h3>Delete post?</h3>
        <form action="" method="POST">
            {% csrf_token %}
            <p>Are you sure you want to delete this post?</p>
            <button type='submit' style="color:red;">Submit</button>
        </form>
</div>
{% endblock %}

posts/templates/posts/search.html
{% extends 'base.html' %}

{% block title %}
all profiles
{% endblock title %}

{% block content %}
{% if profiles %}
{% for obj in profiles %}
<div class="ui segment">
    <div class="ui grid">
        <div class="row">
            <div class="three wide column">
                <img class="ui small circular image" src={{obj.avatar.url}}>
            </div>
            <div class="thirteen wide column">
                <h3>{{obj.user}}</h3>
                <p>{{obj.bio}}</p>
                <a href="{% url 'profiles:get_profile_detail' obj.slug %}"><button
                        class="ui primary button mb-5 w-big">See profile</button></a>
                <br>
                {% if obj.user in rel_receiver and request.user not in obj.friends.all %}
                <button class="ui disabled button mb-5 w-big"><i class="user icon"></i>Waiting for approval</button>
                {% endif %}

                {% if request.user in obj.friends.all %}
                <form action="{% url 'profiles:remove-friend' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="profile_pk" value={{obj.pk}}>
                    <button type="submit" class="ui negative basic button mb-5 w-big"><i
                            class="minus square icon"></i>Remove from friends</button>
                </form>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% else %}
<h1>There is no any user with that name.</h1>
{% endif%}
{% endblock content %}

posts/templates/posts/update.html
{% extends 'base.html' %}
{% block title %}Update{% endblock %}
{% block content %}
<div class='ui segment'>
    <h3>Update post</h3>
    <form action="" method="POST"  enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button type='submit' class="ui button primary mt-5">Update</button>
    </form>
</div>
{% endblock %}